spring:
  application:
    name: kinetix
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=kinetix;encrypt=false;trustServerCertificate=true
    username: sa
    password: ${DB_PASSWORD:password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  flyway:
    enabled: true

server:
  port: 8080

